# Generated by Django 5.1.7 on 2025-03-22 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('details', models.TextField(verbose_name='Детали контракта')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('name', models.CharField(max_length=255, verbose_name='Название производителя')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to='sftapp.contract')),
            ],
            options={
                'verbose_name': 'Кредитная заявка',
                'verbose_name_plural': 'Кредитные заявки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sftapp.manufacturer')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='CreditApplicationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('credit_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_products', to='sftapp.creditapplication')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applications_products', to='sftapp.product')),
            ],
            options={
                'verbose_name': 'Связь кредитной заявки с товаром',
                'verbose_name_plural': 'Связи кредитных заявок с товарами',
                'unique_together': {('credit_application', 'product')},
            },
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='products',
            field=models.ManyToManyField(related_name='credit_applications', through='sftapp.CreditApplicationProduct', to='sftapp.product'),
        ),
    ]
